apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-production
  namespace: default
  labels:
    name: db-config-production
data:
  DYNAMODB_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
  ECR_API: 127096271362.dkr.ecr.us-east-1.amazonaws.com/fastfood-production-api:latest
