apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod-production
  namespace: default
  labels:
    app: api-pod-production
spec:
  template:
    metadata:
      name: api-pod-production
      labels:
        app: api-pod-production
    spec:
      containers:
        - name:  c-api-production
          image: "127096271362.dkr.ecr.us-east-1.amazonaws.com/fastfood-production-api:latest"
          ports:
            - containerPort: 3002
          env:          

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: db-config-production
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: db-config-production
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: db-config-production
                  key: AWS_SESSION_TOKEN           
        
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 5

          resources:
            requests:
              memory: "512Mi"  # Mem칩ria garantida para cada pod
              cpu: "250m"      # CPU garantida para cada pod
            limits:
              memory: "1Gi"    # Mem칩ria m치xima que a pod pode consumir
              cpu: "500m"      # CPU m치xima que a pod pode consumir
  replicas: 1
  selector:
    matchLabels:
      app: api-pod-production
