apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-video-pod
  namespace: default
  labels:
    app: api-video-pod
spec:
  template:
    metadata:
      name: api-video-pod
      labels:
        app: api-video-pod
    spec:
      containers:
        - name:  c-api
          image: 339713138979.dkr.ecr.us-east-1.amazonaws.com/api-framesnap-video:latest
          ports:
            - containerPort: 8082
          env:           

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: AWS_SESSION_TOKEN
                  
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: AWS_REGION        
                  
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: S3_ENDPOINT
                  
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: S3_BUCKET                  
                  
            - name: SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: SQS_QUEUE_URL
                  
            - name: DYNAMO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: DYNAMO_ENDPOINT                  

            - name: DYNAMO_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: DYNAMO_TABLE_NAME

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: REDIS_HOST                  
                  
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: REDIS_PORT
                  
            - name: REDIS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: REDIS_USERNAME                  

            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: video-config
                  key: REDIS_PASSWORD
                  
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
  replicas: 1
  selector:
    matchLabels:
      app: api-video-pod
