apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-video-svc
  name: api-video-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: api-video-pod
  type: LoadBalancer
