apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-production-svc
  name: api-production-loadbalancer-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: api-pod-production
  type: LoadBalancer
